/**
 * CodeGen example API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Class description
 */
export interface Document { 
    /**
     * Identifier
     */
    readonly id?: string;
    /**
     * Title
     */
    readonly title?: string;
    /**
     * Displayed text
     */
    readonly content?: string;
}